### ISSUE TITLE
Default values for tl_content.hofff_toc_max_level inconsistent

### ISSUE THREAD

**Issue by Defcon0** [hofff/contao-content-navigation#21]
Hello,

in `tl_content` the default value definition for the field `hofff_toc_max_level` is inconsistent:

```
    'label'     => &$GLOBALS['TL_LANG']['tl_content']['hofff_toc_max_level'],
    'inputType' => 'select',
    'default'   => '6',
    'exclude'   => true,
    'options'   => ['1', '2', '3', '4', '5', '6'],
    'eval'      => ['tl_class' => 'w50'],
    'sql'       => 'int(1) UNSIGNED NOT NULL default 2',
```

In sql it should also be 6, right? In wouldn't be a BC break because it only takes effect for new records.

Would it be possible to change the sql default value to 6?

Bye Defcon0

**Comment by dmolineus** [comment]
Fixed in release 1.1.4
