### ISSUE TITLE
Als Redakteur (nicht Admin) hat man keine Möglichkeit das Element zu veröffentlichen

### ISSUE THREAD

**Issue by MacKP** [hofff/contao-content-navigation#22]
Mit eingeschränkten Berechtigungen fehlt das Feld 'veröffentlichen' in der Eingabemaske. Ich kann das jetzt nicht gut in einer frischen Installation nachstellen, deswegen kann ich gerade leider nicht sagen, ob es von einer anderen Erweiterung kommt...

Viele Grüße

**Comment by dmolineus** [comment]
Fixed in release 1.1.4
