### ISSUE TITLE
Bitte um Freischschaltung bzw. Anpassung der Erweiterung für Symfony 5

### ISSUE THREAD

**Issue by mec-service** [hofff/contao-content-navigation#24]
Die Erweiterung lässt sich leider bei Contao Version 4.11.2. nicht über den Contao-Manager installieren. 

Wäre es möglich die Extension für Symfony 5 freigeschalten wird bzw. ggf. Anpassungen dafür zu machen, damit die Extension problemloser in einer Contao 4.11+ Installation installiert werden kann?

**Hier ein Auszug aus dem Installations-Logfile:**

$ /usr/bin/php7.4-cli -q -dmax_execution_time=0 -dmemory_limit=-1 -dallow_url_fopen=1 -ddisable_functions= -ddate.timezone=Europe/Berlin /homepages/0/d354724416/htdocs/website-contao/web/contao-manager.phar.php composer require hofff/contao-content-navigation --no-update --no-scripts --prefer-stable --sort-packages --no-ansi --no-interaction

Using version ^1.1 for hofff/contao-content-navigation
/homepages/0/d354724416/htdocs/website-contao/composer.json has been updated

# Process terminated with exit code 0
# Result: OK

> Resolving dependencies using Composer Cloud v3.1.1
!!! Current server is sponsored by: Contao Association !!!

[6.8MiB/0.17s] Loading composer repositories with package information
[55.7MiB/1.99s] Updating dependencies
[1087.0MiB/7.79s] Your requirements could not be resolved to an installable set of packages.
[1087.0MiB/7.80s] 
  Problem 1
    - hofff/contao-content-navigation[1.1.0, ..., 1.1.2] require symfony/dependency-injection ^3.3 || ^4.0 -> satisfiable by symfony/dependency-injection[v3.3.0, ..., v3.4.47, v4.0.0, ..., v4.4.21].
    - symfony/web-profiler-bundle v5.2.6 conflicts with symfony/dependency-injection v4.4.21.
    - symfony/web-profiler-bundle v5.2.6 conflicts with symfony/dependency-injection v4.4.20.
    - symfony/web-profiler-bundle v5.2.6 conflicts with symfony/dependency-injection v4.4.19.
...
...

    - symfony/web-profiler-bundle v5.2.6 conflicts with symfony/dependency-injection v3.3.0.
    - contao/manager-bundle 4.11.2 requires symfony/web-profiler-bundle 4.4.* || 5.2.* -> satisfiable by symfony/web-profiler-bundle[v5.2.6].
    - contao/manager-bundle is locked to version 4.11.2 and an update of this package was not requested.
    - Root composer.json requires hofff/contao-content-navigation ^1.1 -> satisfiable by hofff/contao-content-navigation[1.1.0, 1.1.1, 1.1.2].

[1087.1MiB/7.80s] Running update with --no-dev does not mean require-dev is ignored, it just means the packages will not be installed. If dev requirements are blocking the update you have to resolve those problems.
[44.6MiB/8.74s] Memory usage: 44.62MB (peak: 1088.04MB), time: 8.75s.
[44.6MiB/8.74s] Finished Composer Cloud resolving.

# Cloud Job ID eXvlaHsJRKjNUT5TSQ4VlxrfL8mIyOB7d9oVi64XfiboJyOWHxCms6D8ZNpjck3HktcogYtDqLuJ6TGg3QJWLwXnMj4VV8myFd18 failed

**Comment by dmolineus** [comment]
Done.
