### ISSUE TITLE
Funktioniert nicht bei Include Artikeln auf der Seite

### ISSUE THREAD

**Issue by MacKP** [hofff/contao-content-navigation#8]
Wenn man einen kompletten Artikel per Include auf eine Seite bringt, dann wird in der Navi nichts angezeigt (es wird anscheinend anhand der ParentID überprüft...)

**Comment by dmolineus** [comment]
Das ist derzeit eine Begrenzung. Es werden nur Inhaltselemente ausgelesen, die direkt in einem Artikel existieren. Kommen die aus einer anderen Quelle (z.B. included Artikel oder Newseintrag, dann werden diese ignoriert).
